name: PHP Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']

    steps:
      - uses: actions/checkout@v1

      - name: Install Dependencies (PHP vendors)
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: '7.4'
          extensions: mbstring, intl
          coverage: xdebug

      - name: Run unit test suite
        run: vendor/bin/codecept run unit

      - name: Start server
        run: php bin/console server:start 127.0.0.1:8000

      - name: Run api test suite
        run: vendor/bin/codecept run api
